CREATE TABLE EMPLOYEE
(
	EmpNo INT,
	EmpName VARCHAR(50),
	JoiningDate DATE,
	Salary DECIMAL(8,2),
	City VARCHAR(50)
);

INSERT INTO EMPLOYEE
VAlUES(101,'Keyur','2002-01-05',12000,'Rajkot');
INSERT INTO EMPLOYEE
VAlUES(102,'Hardik','2004-02-15',14000,'Ahmedabad');
INSERT INTO EMPLOYEE
VAlUES(103,'Kajal','2006-03-14',15000,'Baroda');
INSERT INTO EMPLOYEE
VAlUES(104,'Bhoomi','2005-06-23',12500,'Ahmedabad');
INSERT INTO EMPLOYEE
VAlUES(102,'Harmit','2004-02-15',14000,'Rajkot');

SELECT * FROM EMPLOYEE;

--Q1--
SELECT EmpName FROM EMPLOYEE
WHERE Salary>13000 AND City IN('Rajkot','Baroda');
--Q2--
SELECT EmpName FROM EMPLOYEE
ORDER BY EmpName;
--Q3--
SELECT DISTINCT City FROM EMPLOYEE;
--Q4--
UPDATE EMPLOYEE
SET City=NULL
WHERE EmpName='Keyur' OR EmpName='Bhoomi';
--Q5--
SELECT EmpName FROM EMPLOYEE
WHERE City IS NULL;
--Q6--
DELETE FROM EMPLOYEE
WHERE Salary>=14000
--Q7--
DELETE FROM EMPLOYEE
WHERE City='Rajkot';
--Q8--
DELETE FROM EMPLOYEE
WHERE JoiningDate>'2007-01-01';
--Q9--
TRUNCATE TABLE EMPLOYEE;
SELECT * FCROM EMPLOYEE;
--Q10--
DROP TABLE EMPLOYEE;
--Q11--
TRUNCATE TABLE DEPOSIT;
SELECT * FROM DEPOSIT;
--Q12--
DROP TABLE DEPOSIT;
--Q13--
DROP TABLE BRANCH;
--Q14--
DROP TABLE CUSTOMERS;
--Q15--
DROP TABLE BORROW;